version: '3.9'
services:
  app:
    build: .
    container_name: app_container
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./xlsx:/app/xlsx
      - ./xml:/app/xml
      - ./json:/app/json